---
- name: Setup host for GCS Backed hosting
  hosts: localhost
  vars:
    apache_vhosts:
      - {servername: "www.domain.tld", documentroot: "/var/www/html/steinbachonline.com"}
      - {servername: "www.otherdomain.tld", documentroot: "/var/www/html/okotoksonline.com"}
  tasks:
    - name: Install GCS Fuse Yum Repo
      yum_repository:
         baseurl: https://packages.cloud.google.com/yum/repos/gcsfuse-el7-x86_64
         description: "GCS Fuse repository for GCP GCS buckets on VMs"
         gpgcheck: yes
         gpgkey:
            - https://packages.cloud.google.com/yum/doc/yum-key.gpg
            - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         enabled: yes
         name: gcsfuse.repo
         repo_gpgcheck: yes
    - name: Install Apache/PHP
      yum: name=httpd,php
    - name: Yum Update
      yum:  name=* state=latest
    - name: Install gcsfuse
      yum:  name=gcsfuse state=present
    - name: Disable SELinux (MUST be fixed in future version)
      selinux: state=disabled
    - name: start and enable httpd
      systemd:
         enabled: yes
         state: started
         name: httpd
    - name: Mount portal storage bucket
      shell: gcsfuse -o allow_other --implicit-dirs md-gwo-portals /var/www/html
